Update App.kt
KotlinersKt/gist-uploader pull request #3
Opened 2020-10-22 05:48 UTC by pepivsky

Comentario chido. El mejor momento del live de hoy :)

2020-10-22 06:09 UTC, sierisimo requested changes

2020-10-22 06:09 UTC, sierisimo commented on src/main/kotlin/com/kotlinerskt/cli/giskt/App.kt
> + *aguacate no malta XD
IN THIS ORGANIZATION WE RESPECT SPACES!

```suggestion
 * aguacate no malta XD
```

2020-10-22 06:13 UTC, ChubyAvodroc requested changes
Check comments please

2020-10-22 06:13 UTC, ChubyAvodroc commented on src/main/kotlin/com/kotlinerskt/cli/giskt/App.kt
> + *aguacate no malta XD
QUÉ ES MALTA 🧐🧐🧐

```suggestion
 *aguacate no palta XD
```

2020-10-27 22:19 UTC, gorrotowi approved these changes

2020-10-27 22:22 UTC, merged